# .readthedocs.yml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-4.10"
  jobs:
    pre_build:
      # Generate the Sphinx configuration for this Jupyter Book so it builds.
      - "jupyter-book config sphinx docs/"

conda:
  environment: docs_environment.yml

submodules:
  include:
    - doc/notebooks
    - pybind11
  recursive: true


python:
  install:
    - method: pip
      path: .
      extra_requirements:
      - sphinx

sphinx:
  builder: html
  fail_on_warning: false
